import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  book: [
    {
      type: "category",
      label: "Part 1 — Introduction",
      collapsed: false,
      link: { type: "doc", id: "introduction/index" },
      items: ["introduction/how-to-use", "introduction/study-plan"],
    },
    {
      type: "category",
      label: "Part 2 — Foundations",
      link: { type: "doc", id: "foundations/index" },
      items: [
        "foundations/typescript",
        "foundations/javascript-browser",
        "foundations/html-css",
        "foundations/accessibility",
        "foundations/browser-apis",
      ],
    },
    {
      type: "category",
      label: "Part 3 — Modern React",
      link: { type: "doc", id: "react/index" },
      items: [
        "react/mental-model",
        "react/hooks-deep-dive",
        "react/suspense-concurrent",
        "react/server-vs-client",
        "react/state-management",
        "react/forms",
        "react/performance-intro",
        "react/testing-intro",
      ],
    },
    {
      type: "category",
      label: "Part 4 — Next.js",
      link: { type: "doc", id: "nextjs/index" },
      items: [
        "nextjs/app-vs-pages",
        "nextjs/layouts-routing",
        "nextjs/data-fetching-caching",
        "nextjs/server-actions",
        "nextjs/middleware-edge",
        "nextjs/auth-integration",
        "nextjs/deployment",
      ],
    },
    {
      type: "category",
      label: "Part 5 — Angular Basics",
      link: { type: "doc", id: "angular-basics/index" },
      items: [
        "angular-basics/components-modules",
        "angular-basics/di",
        "angular-basics/rxjs",
        "angular-basics/routing",
        "angular-basics/forms",
        "angular-basics/http",
        "angular-basics/signals",
        "angular-basics/react-equivalent",
      ],
    },
    {
      type: "category",
      label: "Part 6 — Frontend Architecture",
      link: { type: "doc", id: "fe-architecture/index" },
      items: [
        "fe-architecture/component-patterns",
        "fe-architecture/design-systems",
        "fe-architecture/state-machines",
        "fe-architecture/project-structure",
        "fe-architecture/micro-frontends",
      ],
    },
    {
      type: "category",
      label: "Part 7 — Production Concerns",
      link: { type: "doc", id: "production-concerns/index" },
      items: [
        "production-concerns/performance",
        "production-concerns/testing-strategy",
        "production-concerns/observability",
        "production-concerns/build-tooling",
        "production-concerns/cicd-feature-flags",
        "production-concerns/i18n",
        "production-concerns/pwa-offline",
        "production-concerns/ai-features",
      ],
    },
    {
      type: "category",
      label: "Part 8 — Node.js Backend",
      link: { type: "doc", id: "nodejs-backend/index" },
      items: [
        "nodejs-backend/node-fundamentals",
        "nodejs-backend/project-setup",
        "nodejs-backend/express",
        "nodejs-backend/fastify",
        "nodejs-backend/nestjs",
        "nodejs-backend/comparison",
      ],
    },
    {
      type: "category",
      label: "Part 9 — REST APIs & Networking",
      link: { type: "doc", id: "rest-and-networking/index" },
      items: [
        "rest-and-networking/rest-principles",
        "rest-and-networking/pagination-filtering",
        "rest-and-networking/versioning-idempotency",
        "rest-and-networking/errors",
        "rest-and-networking/openapi",
        "rest-and-networking/http-and-tls",
        "rest-and-networking/realtime",
        "rest-and-networking/graphql-trpc",
      ],
    },
    {
      type: "category",
      label: "Part 10 — Authentication & Authorization",
      link: { type: "doc", id: "auth/index" },
      items: [
        "auth/authn-vs-authz",
        "auth/sessions-vs-jwt",
        "auth/oauth-oidc",
        "auth/cookies",
        "auth/refresh-tokens",
        "auth/rbac-abac",
        "auth/implementations",
        "auth/react-client",
      ],
    },
    {
      type: "category",
      label: "Part 11 — Security & Privacy",
      link: { type: "doc", id: "security-and-privacy/index" },
      items: [
        "security-and-privacy/owasp",
        "security-and-privacy/xss-csp",
        "security-and-privacy/csrf",
        "security-and-privacy/cors",
        "security-and-privacy/other-attacks",
        "security-and-privacy/secrets-tls-rate-limiting",
        "security-and-privacy/privacy-gdpr",
      ],
    },
    {
      type: "category",
      label: "Part 12 — AWS for Frontend Engineers",
      link: { type: "doc", id: "aws/index" },
      items: [
        "aws/iam",
        "aws/s3",
        "aws/cloudfront-route53",
        "aws/lambda",
        "aws/api-gateway",
        "aws/dynamodb",
        "aws/cognito",
        "aws/messaging",
        "aws/cloudwatch",
        "aws/secrets-ssm",
        "aws/end-to-end",
      ],
    },
    {
      type: "category",
      label: "Part 13 — Interview Prep Toolkit",
      link: { type: "doc", id: "interview-prep/index" },
      items: [
        "interview-prep/system-design-framework",
        "interview-prep/worked-chat",
        "interview-prep/worked-dashboard",
        "interview-prep/worked-feed",
        "interview-prep/worked-uploader",
        "interview-prep/worked-autocomplete",
        "interview-prep/worked-collab",
        "interview-prep/behavioral",
        "interview-prep/leadership",
        "interview-prep/take-home-and-review",
      ],
    },
    "glossary",
  ],
};

export default sidebars;
